- hosts: localhost
  gather_facts: yes
  tasks:
  become: true
  tasks:
    - name: download Repository Deb File
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb
        dest: /opt/zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: Adding Repo
      apt:
        deb: /opt/zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: To Update the cache
      apt:
        update_cache: yes



    - name: install zabbix agent
      apt:
        name: zabbix-agent2
        state: latest

    - name:  Start zabbix-agent2 service
      service:
        name: zabbix-agent2
        state: started
